[features]
seeds = false
skip-lint = false
[programs.localnet]
aim_staking_program = "2EYmHbfTeFYMc5xNjXp4pd1Y6M2b4fLdrWPucwMHSAJz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/havencross/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000
