[features]
seeds = false
skip-lint = false
[programs.devnet]
aim_staking_program = "DdB4xNCwXYoVfanj9Kek3CWJN1jDD9MZXxLeAYnh5u4Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/havencross/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000
