[features]
seeds = false
skip-lint = false
[programs.devnet]
aim_staking_program_v2 = "FG8P631H9q5b53qsVM9aD71GZTWBKvujtqeWUGstpeka"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/havencross/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000
