[features]
seeds = false
skip-lint = false
[programs.localnet]
aim_staking_program = "5BH7DL2muAL9w3LYcZWcB1U8JA1dc7KFaCfTpKJ5RjmD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/havencross/.config/solana/id.json"

[scripts]
test = "RUSTFLAGS='-Cinstrument-coverage' CARGO_INCREMENTAL=0 LLVM_PROFILE_FILE='target/coverage/aim_staking_program-%p-%m.profraw' yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000
